### PR TITLE
fix #47

### LINKED ISSUE #47: library(memisc) causes functions to print NAMESPACE cache information
Hi,

It would appear that attaching both the memisc and the tibble R packages causes certain functions to print text about caches and NAMESPACES. For example, I've included a reproducible version below (tested with memisc CRAN version 0.99.25.6 and GitHub version 0.99.26.3):

```
# load packages
library(tibble)
library(memisc)

# create data
d <- tibble(value = seq(0, 100))

# subset data
subset_d <- subset(d, d$value < 50)
# Found more than one class "tbl_df" in cache; using the first, from namespace 'tibble'
# Also defined by ‘memisc’
# Found more than one class "tbl_df" in cache; using the first, from namespace 'tibble'
# Also defined by ‘memisc’
``` 

Although this text isn't a warning -- and nor is it an error message -- it could potentially cause issues from some users? One of the packages I contribute to had a [similar issue a while ago](https://github.com/prioritizr/prioritizr/issues/75), and [@davidcanarte reported that they are currently experiencing this issue with the memisc R package and was looking for a fix](https://github.com/prioritizr/prioritizr/issues/157). I believe this issue is due to defining `tbl_df` as a S4 class in the memisc R package (i.e. [`setOldClass("tbl_df")`](https://github.com/melff/memisc/blob/37ab351ba3db9e12020a612f37f2d94a2279bd4e/pkg/R/tibbles.R#L146)) when the tibble R package defines [`tbl_df` as an S4 class](https://github.com/tidyverse/tibble/blob/master/NAMESPACE#L73)? Therefore, a potential fix could involve (1) removing the `setOldClass("tbl_df")` code and (2) updating the NAMESPACE file to import the `tbl_df` S4 class from the tibble R package. This would also require (3) listing the tibble R package under `Imports` and not `Enhances` in the DESCRIPTION file. What do you think?

I've verified that this approach fixes the issue locally (i.e. by running the example code above on an updated fork of the memisc GitHub repository). In case this is helpful, I've submitted a PR with the proposed fix. I've bumped the version to 0.99.26.4, but please let me know if you need any additional updates to merge the PR?

### PR DESCRIPTION
**Pull request by jeffreyhanson**
This PR fixes #47. Please refer to this issue for more details. @davidcanarte, if you install this fork -- e.g. using the R code: `devtools::install_github("jeffreyhanson/memisc")` -- this should fix the issue in your analysis code.

### CODE REVIEW

**Comment by melff** [comment]
The proposed change would create a dependency of 'memisc' on 'tibble' via the 'imports' relation. This would make maintaining the packages more difficult than necessary because the dependence of 'tibble' on other 'tidyverse' package and the interdependence of those many 'tidyverse' packages.

A far less intrusive change would be making the call `setOldClass("tbl_df")` conditional on the class definition not yet being present, i.e. prepending it with something like `if(!("tibble" %in% loadedNamespaces()))`.

**Comment by melff** [comment]
Fixed by commit d5ee76685e7f29c74c6dac332c89e201868630fa.

**Comment by davidcanarte** [comment]
Hello Martin

I think I am a little lost where to make the call suggested below my email for fixing the warning messages "Found more than one class "tbl_df" in cache; using the first, from namespace 'tibble'
Also defined by ‘memisc’”

Where should make this call "setOldClass("tbl_df”)”? At the beginning of my script?

Thanks

David Cañarte
Ph.D. Candidate
Department of Sociology
and Criminology
University of Florida
dcanarte@ufl.edu<mailto:dcanarte@ufl.edu>

On Aug 12, 2020, at 5:56 AM, Martin Elff <notifications@github.com<mailto:notifications@github.com>> wrote:

[External Email]


The proposed change would create a dependency of 'memisc' on 'tibble' via the 'imports' relation. This would make maintaining the packages more difficult than necessary because the dependence of 'tibble' on other 'tidyverse' package and the interdependence of those many 'tidyverse' packages.

A far less intrusive change would be making the call setOldClass("tbl_df") conditional on the class definition not yet being present, i.e. prepending it with something like if(!("tibble" %in% loadedNamespaces())).

**Comment by melff** [comment]
The problem should be fixed with the latest commit. You can install it with `devtools::install_github("melff/memisc",subdir="pkg")`. No need for you to anything other than that.

**Comment by davidcanarte** [comment]
Thank you! Do I have to make this call one time or every time I am working on a (several different) project(s)?

David Cañarte
Ph.D. Candidate
Department of Sociology
and Criminology
University of Florida
dcanarte@ufl.edu<mailto:dcanarte@ufl.edu>

On Aug 14, 2020, at 1:04 PM, Martin Elff <notifications@github.com<mailto:notifications@github.com>> wrote:

devtools::install_github("melff/memisc",subdir="pkg")

**Comment by melff** [comment]
Only one time - just like `install.packages()`. You will need to install the "devtools" package first, however.

**Comment by davidcanarte** [comment]
Trying again because I did not load devtools before making this call. Thank you very much

David Cañarte
Ph.D. Candidate
Department of Sociology
and Criminology
University of Florida
dcanarte@ufl.edu<mailto:dcanarte@ufl.edu>

On Aug 14, 2020, at 2:57 PM, Martin Elff <notifications@github.com<mailto:notifications@github.com>> wrote:

[External Email]


Only one time - just like install.packages(). You will need to install the "devtools" package first, however.

**Pull request closed without merging**
